apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: localist
data:
  NODE_ENV: "production"
  PORT: "3001"
  LOG_LEVEL: "info"
  CORS_ORIGIN: "https://localist.leopaska.xyz"
  FRONTEND_URL: "https://localist.leopaska.xyz"
  DISABLE_VENUE_SCRAPER: "true"
  RUN_MIGRATIONS: "true"
  DB_SSL: "false"
  DB_NAME: "localist"
  DB_HOST: "external-postgres.default.svc.cluster.local"
  DB_PORT: "5432"
  POSTGRES_HOST: "external-postgres.default.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "localist"
  POSTGRES_USER: "postgres"
  REDIS_HOST: "external-redis.default.svc.cluster.local"
  REDIS_PORT: "6379"

