apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: localist
data:
  NODE_ENV: "production"
  PORT: "3001"
  LOG_LEVEL: "info"
  CORS_ORIGIN: "https://localist.leopaska.xyz"
  DISABLE_VENUE_SCRAPER: "true"
  RUN_MIGRATIONS: "true"

