apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: localist

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - backend-deployment.yaml

labels:
  - pairs:
      app.kubernetes.io/name: localist-backend
      app.kubernetes.io/managed-by: kustomize

# Image tag will be overridden by overlays
# images:
#   - name: localist/backend
#     newTag: v7

replicas:
  - name: backend
    count: 1


